spring:
  applacation:
    name: HaiouMedia
    version: 1.0.0
  datasource:
    url: jdbc:mysql://localhost:3306/media?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    # tomcat?URI??
    uri-encoding: UTF-8
    # tomcat?????????200
    max-threads: 800
    # Tomcat?????????????25
    min-spare-threads: 30

upload:
  chunk-size: 5242880
  temp-dir: /tmp/upload
  final-dir: /data/media